//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cennik
    {
        public int ID { get; set; }
        public Nullable<decimal> MinWaga { get; set; }
        public Nullable<decimal> MaxWaga { get; set; }
        public Nullable<decimal> Cena { get; set; }
    }
}
