//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cennik
    {

        public int ID { get; set; }

        [Display(Name="Minimalna waga")]
        public Nullable<decimal> MinWaga { get; set; }

        [Display(Name = "Maksymalna waga")]
        public Nullable<decimal> MaxWaga { get; set; }

        [Display(Name = "Cena waga")]
        public Nullable<decimal> Cena { get; set; }
    }
}
