//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naprawa
    {
        public int ID { get; set; }
        public int FK_Samochod { get; set; }
        public int FK_Serwis { get; set; }
        public System.DateTime DataOddania { get; set; }
        public System.DateTime DataOdbioru { get; set; }
        public string Opis { get; set; }
    
        public virtual Samochod Samochod { get; set; }
        public virtual Serwis Serwis { get; set; }
    }
}
