//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odbior
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odbior()
        {
            this.Zlecenie = new HashSet<Zlecenie>();
        }
    
        public int ID { get; set; }

        [Display(Name = "Klient")]
        public int FK_Klient { get; set; }

        [Display(Name = "Data odbioru")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Data { get; set; }

        [NotMapped]
        [Display(Name = "Nadanie")]
        public string Opis { get { return Data + ": " + Klient.ImieNazwisko; } }
        public virtual Klient Klient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zlecenie> Zlecenie { get; set; }
    }
}
