//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paczka
    {
        public int ID { get; set; }
        public int FK_Zlecenie { get; set; }
        public int FK_Przewoz { get; set; }
        public string Nazwa { get; set; }
        public decimal Wartosc { get; set; }
        public decimal Waga { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Przewoz Przewoz { get; set; }
        public virtual Zlecenie Zlecenie { get; set; }
    }
}
