//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paczka
    {
        public int ID { get; set; }

        [Display(Name= "Zlecenie")]
        public int FK_Zlecenie { get; set; }

        [Display(Name = "Przewóz")]
        public int FK_Przewoz { get; set; }

        [Display(Name = "Nazwa")]
        public string Nazwa { get; set; }

        [Display(Name = "Wartosc")]
        public decimal Wartosc { get; set; }

        [Display(Name = "Waga")]
        public decimal Waga { get; set; }

        [Display(Name = "Uwagi")]
        public string Uwagi { get; set; }

        [Display(Name = "Przewóz")]
        public virtual Przewoz Przewoz { get; set; }

        [Display(Name = "Zlecenie")]
        public virtual Zlecenie Zlecenie { get; set; }
    }
}
