//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przewoz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Przewoz()
        {
            this.Paczka = new HashSet<Paczka>();
        }
    
        public int ID { get; set; }

        [Display(Name="Samochód")]
        public int FK_Samochod { get; set; }

        [Display(Name = "Kierowca")]
        public int FK_Kierowca { get; set; }

        [Display(Name = "Data przewozu")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DataPrzewozu { get; set; }

        [NotMapped]
        [Display(Name = "Przewóz:")]
        public string Opis { get
        {
            return DataPrzewozu + ", " + Kierowca.ImieNazwisko + ", " + Samochod.MarkaModelNumerRej;
        } }

        [Display(Name = "Kierowca")]
        public virtual Kierowca Kierowca { get; set; }

        [Display(Name = "Paczka")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paczka> Paczka { get; set; }

        [Display(Name = "Samochód")]
        public virtual Samochod Samochod { get; set; }
    }
}
