//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serwis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serwis()
        {
            this.Naprawa = new HashSet<Naprawa>();
        }
    
        public int FK_Uzytkownik { get; set; }
        public string Nazwa { get; set; }
        public string KodPocztowy { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public decimal NumerDomu { get; set; }
        public Nullable<decimal> NumerMieszkania { get; set; }
        public decimal Telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Naprawa> Naprawa { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
