//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uprawnienia
    {
        public int ID { get; set; }

        [Display(Name = "Kierowca")]
        public int FK_Kierowca { get; set; }

        [Display(Name = "Numer uprawnienia")]
        public string NumerUprawnienia { get; set; }

        [Display(Name = "Opis")]
        public string Opis { get; set; }

        [Display(Name = "Data od")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DataOd { get; set; }

        [Display(Name = "Data do")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DataDo { get; set; }
    
        public virtual Kierowca Kierowca { get; set; }
    }
}
