//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uprawnienia
    {
        public int ID { get; set; }
        public int FK_Kierowca { get; set; }
        public string NumerUprawnienia { get; set; }
        public string Opis { get; set; }
        public System.DateTime DataOd { get; set; }
        public System.DateTime DataDo { get; set; }
    
        public virtual Kierowca Kierowca { get; set; }
    }
}
