//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownik
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Hasło { get; set; }
        public string Typ { get; set; }
    
        public virtual Kierowca Kierowca { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Serwis Serwis { get; set; }
    }
}
