//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBD_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zlecenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zlecenie()
        {
            this.Paczka = new HashSet<Paczka>();
        }
    
        public int ID { get; set; }
        public int FK_Realizacja { get; set; }
        public int FK_Nadanie { get; set; }
        public int FK_Odbior { get; set; }
        public int FK_Pracownik { get; set; }
        public string Lokalizacja { get; set; }
        public System.DateTime DataZlecenia { get; set; }
    
        public virtual Nadanie Nadanie { get; set; }
        public virtual Odbior Odbior { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paczka> Paczka { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Realizacja Realizacja { get; set; }
    }
}
